[features]
seeds = false
skip-lint = false
[programs.localnet]
rocket = "7vWEUWH7L9VJCZjVahFwpWstZqfmGTSK122VVtvdvzFz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/stacc/g3s.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
