[features]
seeds = false
skip-lint = false
[programs.localnet]
rocket = "H9jRj2YszfK6tHPA7UrsnqxXeY9avZYqYFhNzXApxYhw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/jd/g3s.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
